### ISSUE TITLE
Developers at Etsy?

### ISSUE THREAD

**Issue by sealabcore** [kytrinyx/etsy#103]
We are having a massive issue with Etsy API at the moment, and their developer support is not responding.

Does anybody have any contacts at Etsy that they can send me? Any help would be appreciated.

Thanks guys!

**Comment by kytrinyx** [comment]
I'm afraid I don't know any of the developers there. I asked them if they wanted to take over the gem a while back, but their devs do mostly PHP and JavaScript, it seems, not Ruby developers. Sorry :(

**Comment by sealabcore** [comment]
Thanks @kytrinyx ! I will wait for their official response through their normal support channels.

**Comment by danielsz** [comment]
Me too, I've had a hard time trying to contact Etsy dev support.

If you find a responsive channel, would you kindly share it. Thank you!
