### ISSUE TITLE
400 Error on New Listing

### ISSUE THREAD

**Issue by iyerushalmi** [kytrinyx/etsy#104]
I am getting a 400 error when trying to create a new listing:
```
		@listing = Etsy::Listing.create(@access.merge(
			title: "test",
			description: "test description",
			quantity: 10,
			price: 5.5,
			who_made: "someone_else",
			is_supply: true,
			when_made: "before_1997",
			state: "draft",
			shipping_template_id: 12605497
		))
```
Any idea why this might be? I am able to successfully make other API calls...

**Comment by kytrinyx** [comment]
Yeah, probably the API changed since the Listing thing was created. I've actually never used the `Listing` thing--I always just used the query syntax described in the README. Admittedly, it's been a long time since I worked on any Etsy apps, which makes it harder to catch these things when they get out of date.

**Comment by iyerushalmi** [comment]
Hmmm I also tried this and it returned a 404 error:

```
@listing = Etsy::Request.get('/listings', @access.merge(
			title: "testing title",
			description: "test description test description test description test description",
			quantity: "10",
			price: "5",
			who_made: "someone_else",
			is_supply: true,
			when_made: "before_1997"))
```

Any idea why that might be?

**Comment by kytrinyx** [comment]
That's a `get` request. It looks like you're trying to create a listing, which would probably be a `post` request.

**Comment by iyerushalmi** [comment]
In the end it was that, as well as an authorization issue. Thank you for your help

**Comment by kytrinyx** [comment]
Glad you got it sorted!
