### ISSUE TITLE
Store and Reuse an AccessToken?

### ISSUE THREAD

**Issue by asecondwill** [kytrinyx/etsy#126]
Hi

Sorry to ask, but is it possible to store an accessToken and reuse?  I want to be able to poll for new receipts hourly, without having to manually be there to get the code from etsy each time.

**Comment by kytrinyx** [comment]
Hi @asecondwill, that's a good question!

I assume you can store your token in an environment variable and initialize a new Etsy client with the stored variable.

We aren't planning on adding a storage mechanism to the Etsy client itself.

**Comment by asecondwill** [comment]
@kytrinyx  - ok, thanks.  That hasn't been working for me but Ill keep trying to figure out the details of it this week & update this in case somebody else is interested.

**Comment by zener79** [comment]
Hi @asecondwill,
did you managed to reuse the AccessToken?
